// Example IDL file for our monster's schema.

namespace coms309.server;

struct Player {
    pid:long;
    id:long;
}

table GameState {
  difficulty:short;
  state:short;
  mapId:long;
  round:short;
  players:Player;
}

root_type GameState;
