// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataObject.proto

package coms309.server.Schema;

/**
 * Protobuf type {@code coms309.server.DataObjectSchema}
 */
public  final class DataObjectSchema extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coms309.server.DataObjectSchema)
    DataObjectSchemaOrBuilder {
  // Use DataObjectSchema.newBuilder() to construct.
  private DataObjectSchema(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DataObjectSchema() {
    timestamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DataObjectSchema(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            bitField0_ |= 0x00000001;
            timestamp_ = input.readInt64();
            break;
          }
          case 18: {
            coms309.server.Schema.GamestateSchema.Builder subBuilder = null;
            if (dataCase_ == 2) {
              subBuilder = ((coms309.server.Schema.GamestateSchema) data_).toBuilder();
            }
            data_ =
                input.readMessage(coms309.server.Schema.GamestateSchema.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((coms309.server.Schema.GamestateSchema) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 2;
            break;
          }
          case 26: {
            coms309.server.Schema.MessageSchema.Builder subBuilder = null;
            if (dataCase_ == 3) {
              subBuilder = ((coms309.server.Schema.MessageSchema) data_).toBuilder();
            }
            data_ =
                input.readMessage(coms309.server.Schema.MessageSchema.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((coms309.server.Schema.MessageSchema) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 3;
            break;
          }
          case 34: {
            coms309.server.Schema.EntitySchema.Builder subBuilder = null;
            if (dataCase_ == 4) {
              subBuilder = ((coms309.server.Schema.EntitySchema) data_).toBuilder();
            }
            data_ =
                input.readMessage(coms309.server.Schema.EntitySchema.PARSER, extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((coms309.server.Schema.EntitySchema) data_);
              data_ = subBuilder.buildPartial();
            }
            dataCase_ = 4;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_DataObjectSchema_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_DataObjectSchema_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            coms309.server.Schema.DataObjectSchema.class, coms309.server.Schema.DataObjectSchema.Builder.class);
  }

  private int bitField0_;
  private int dataCase_ = 0;
  private java.lang.Object data_;
  public enum DataCase
      implements com.google.protobuf.Internal.EnumLite {
    GAMESTATE(2),
    MESSAGE(3),
    ENTITY(4),
    DATA_NOT_SET(0);
    private final int value;
    private DataCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DataCase valueOf(int value) {
      return forNumber(value);
    }

    public static DataCase forNumber(int value) {
      switch (value) {
        case 2: return GAMESTATE;
        case 3: return MESSAGE;
        case 4: return ENTITY;
        case 0: return DATA_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public DataCase
  getDataCase() {
    return DataCase.forNumber(
        dataCase_);
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 1;
  private long timestamp_;
  /**
   * <code>required int64 timestamp = 1;</code>
   */
  public boolean hasTimestamp() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>required int64 timestamp = 1;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  public static final int GAMESTATE_FIELD_NUMBER = 2;
  /**
   * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
   */
  public boolean hasGamestate() {
    return dataCase_ == 2;
  }
  /**
   * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
   */
  public coms309.server.Schema.GamestateSchema getGamestate() {
    if (dataCase_ == 2) {
       return (coms309.server.Schema.GamestateSchema) data_;
    }
    return coms309.server.Schema.GamestateSchema.getDefaultInstance();
  }
  /**
   * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
   */
  public coms309.server.Schema.GamestateSchemaOrBuilder getGamestateOrBuilder() {
    if (dataCase_ == 2) {
       return (coms309.server.Schema.GamestateSchema) data_;
    }
    return coms309.server.Schema.GamestateSchema.getDefaultInstance();
  }

  public static final int MESSAGE_FIELD_NUMBER = 3;
  /**
   * <code>optional .coms309.server.MessageSchema message = 3;</code>
   */
  public boolean hasMessage() {
    return dataCase_ == 3;
  }
  /**
   * <code>optional .coms309.server.MessageSchema message = 3;</code>
   */
  public coms309.server.Schema.MessageSchema getMessage() {
    if (dataCase_ == 3) {
       return (coms309.server.Schema.MessageSchema) data_;
    }
    return coms309.server.Schema.MessageSchema.getDefaultInstance();
  }
  /**
   * <code>optional .coms309.server.MessageSchema message = 3;</code>
   */
  public coms309.server.Schema.MessageSchemaOrBuilder getMessageOrBuilder() {
    if (dataCase_ == 3) {
       return (coms309.server.Schema.MessageSchema) data_;
    }
    return coms309.server.Schema.MessageSchema.getDefaultInstance();
  }

  public static final int ENTITY_FIELD_NUMBER = 4;
  /**
   * <code>optional .coms309.server.EntitySchema entity = 4;</code>
   */
  public boolean hasEntity() {
    return dataCase_ == 4;
  }
  /**
   * <code>optional .coms309.server.EntitySchema entity = 4;</code>
   */
  public coms309.server.Schema.EntitySchema getEntity() {
    if (dataCase_ == 4) {
       return (coms309.server.Schema.EntitySchema) data_;
    }
    return coms309.server.Schema.EntitySchema.getDefaultInstance();
  }
  /**
   * <code>optional .coms309.server.EntitySchema entity = 4;</code>
   */
  public coms309.server.Schema.EntitySchemaOrBuilder getEntityOrBuilder() {
    if (dataCase_ == 4) {
       return (coms309.server.Schema.EntitySchema) data_;
    }
    return coms309.server.Schema.EntitySchema.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasTimestamp()) {
      memoizedIsInitialized = 0;
      return false;
    }
    if (hasMessage()) {
      if (!getMessage().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    if (hasEntity()) {
      if (!getEntity().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, timestamp_);
    }
    if (dataCase_ == 2) {
      output.writeMessage(2, (coms309.server.Schema.GamestateSchema) data_);
    }
    if (dataCase_ == 3) {
      output.writeMessage(3, (coms309.server.Schema.MessageSchema) data_);
    }
    if (dataCase_ == 4) {
      output.writeMessage(4, (coms309.server.Schema.EntitySchema) data_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, timestamp_);
    }
    if (dataCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (coms309.server.Schema.GamestateSchema) data_);
    }
    if (dataCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (coms309.server.Schema.MessageSchema) data_);
    }
    if (dataCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (coms309.server.Schema.EntitySchema) data_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof coms309.server.Schema.DataObjectSchema)) {
      return super.equals(obj);
    }
    coms309.server.Schema.DataObjectSchema other = (coms309.server.Schema.DataObjectSchema) obj;

    boolean result = true;
    result = result && (hasTimestamp() == other.hasTimestamp());
    if (hasTimestamp()) {
      result = result && (getTimestamp()
          == other.getTimestamp());
    }
    result = result && getDataCase().equals(
        other.getDataCase());
    if (!result) return false;
    switch (dataCase_) {
      case 2:
        result = result && getGamestate()
            .equals(other.getGamestate());
        break;
      case 3:
        result = result && getMessage()
            .equals(other.getMessage());
        break;
      case 4:
        result = result && getEntity()
            .equals(other.getEntity());
        break;
      case 0:
      default:
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
    }
    switch (dataCase_) {
      case 2:
        hash = (37 * hash) + GAMESTATE_FIELD_NUMBER;
        hash = (53 * hash) + getGamestate().hashCode();
        break;
      case 3:
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
        break;
      case 4:
        hash = (37 * hash) + ENTITY_FIELD_NUMBER;
        hash = (53 * hash) + getEntity().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static coms309.server.Schema.DataObjectSchema parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static coms309.server.Schema.DataObjectSchema parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static coms309.server.Schema.DataObjectSchema parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static coms309.server.Schema.DataObjectSchema parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static coms309.server.Schema.DataObjectSchema parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static coms309.server.Schema.DataObjectSchema parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static coms309.server.Schema.DataObjectSchema parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static coms309.server.Schema.DataObjectSchema parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static coms309.server.Schema.DataObjectSchema parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static coms309.server.Schema.DataObjectSchema parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(coms309.server.Schema.DataObjectSchema prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code coms309.server.DataObjectSchema}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coms309.server.DataObjectSchema)
      coms309.server.Schema.DataObjectSchemaOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_DataObjectSchema_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_DataObjectSchema_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coms309.server.Schema.DataObjectSchema.class, coms309.server.Schema.DataObjectSchema.Builder.class);
    }

    // Construct using coms309.server.Schema.DataObjectSchema.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      timestamp_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      dataCase_ = 0;
      data_ = null;
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_DataObjectSchema_descriptor;
    }

    public coms309.server.Schema.DataObjectSchema getDefaultInstanceForType() {
      return coms309.server.Schema.DataObjectSchema.getDefaultInstance();
    }

    public coms309.server.Schema.DataObjectSchema build() {
      coms309.server.Schema.DataObjectSchema result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public coms309.server.Schema.DataObjectSchema buildPartial() {
      coms309.server.Schema.DataObjectSchema result = new coms309.server.Schema.DataObjectSchema(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.timestamp_ = timestamp_;
      if (dataCase_ == 2) {
        if (gamestateBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = gamestateBuilder_.build();
        }
      }
      if (dataCase_ == 3) {
        if (messageBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = messageBuilder_.build();
        }
      }
      if (dataCase_ == 4) {
        if (entityBuilder_ == null) {
          result.data_ = data_;
        } else {
          result.data_ = entityBuilder_.build();
        }
      }
      result.bitField0_ = to_bitField0_;
      result.dataCase_ = dataCase_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof coms309.server.Schema.DataObjectSchema) {
        return mergeFrom((coms309.server.Schema.DataObjectSchema)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(coms309.server.Schema.DataObjectSchema other) {
      if (other == coms309.server.Schema.DataObjectSchema.getDefaultInstance()) return this;
      if (other.hasTimestamp()) {
        setTimestamp(other.getTimestamp());
      }
      switch (other.getDataCase()) {
        case GAMESTATE: {
          mergeGamestate(other.getGamestate());
          break;
        }
        case MESSAGE: {
          mergeMessage(other.getMessage());
          break;
        }
        case ENTITY: {
          mergeEntity(other.getEntity());
          break;
        }
        case DATA_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      if (!hasTimestamp()) {
        return false;
      }
      if (hasMessage()) {
        if (!getMessage().isInitialized()) {
          return false;
        }
      }
      if (hasEntity()) {
        if (!getEntity().isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      coms309.server.Schema.DataObjectSchema parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (coms309.server.Schema.DataObjectSchema) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int dataCase_ = 0;
    private java.lang.Object data_;
    public DataCase
        getDataCase() {
      return DataCase.forNumber(
          dataCase_);
    }

    public Builder clearData() {
      dataCase_ = 0;
      data_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private long timestamp_ ;
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    public Builder setTimestamp(long value) {
      bitField0_ |= 0x00000001;
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 timestamp = 1;</code>
     */
    public Builder clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestamp_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        coms309.server.Schema.GamestateSchema, coms309.server.Schema.GamestateSchema.Builder, coms309.server.Schema.GamestateSchemaOrBuilder> gamestateBuilder_;
    /**
     * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
     */
    public boolean hasGamestate() {
      return dataCase_ == 2;
    }
    /**
     * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
     */
    public coms309.server.Schema.GamestateSchema getGamestate() {
      if (gamestateBuilder_ == null) {
        if (dataCase_ == 2) {
          return (coms309.server.Schema.GamestateSchema) data_;
        }
        return coms309.server.Schema.GamestateSchema.getDefaultInstance();
      } else {
        if (dataCase_ == 2) {
          return gamestateBuilder_.getMessage();
        }
        return coms309.server.Schema.GamestateSchema.getDefaultInstance();
      }
    }
    /**
     * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
     */
    public Builder setGamestate(coms309.server.Schema.GamestateSchema value) {
      if (gamestateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        gamestateBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
     */
    public Builder setGamestate(
        coms309.server.Schema.GamestateSchema.Builder builderForValue) {
      if (gamestateBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        gamestateBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
     */
    public Builder mergeGamestate(coms309.server.Schema.GamestateSchema value) {
      if (gamestateBuilder_ == null) {
        if (dataCase_ == 2 &&
            data_ != coms309.server.Schema.GamestateSchema.getDefaultInstance()) {
          data_ = coms309.server.Schema.GamestateSchema.newBuilder((coms309.server.Schema.GamestateSchema) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 2) {
          gamestateBuilder_.mergeFrom(value);
        }
        gamestateBuilder_.setMessage(value);
      }
      dataCase_ = 2;
      return this;
    }
    /**
     * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
     */
    public Builder clearGamestate() {
      if (gamestateBuilder_ == null) {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 2) {
          dataCase_ = 0;
          data_ = null;
        }
        gamestateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
     */
    public coms309.server.Schema.GamestateSchema.Builder getGamestateBuilder() {
      return getGamestateFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
     */
    public coms309.server.Schema.GamestateSchemaOrBuilder getGamestateOrBuilder() {
      if ((dataCase_ == 2) && (gamestateBuilder_ != null)) {
        return gamestateBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 2) {
          return (coms309.server.Schema.GamestateSchema) data_;
        }
        return coms309.server.Schema.GamestateSchema.getDefaultInstance();
      }
    }
    /**
     * <code>optional .coms309.server.GamestateSchema gamestate = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        coms309.server.Schema.GamestateSchema, coms309.server.Schema.GamestateSchema.Builder, coms309.server.Schema.GamestateSchemaOrBuilder> 
        getGamestateFieldBuilder() {
      if (gamestateBuilder_ == null) {
        if (!(dataCase_ == 2)) {
          data_ = coms309.server.Schema.GamestateSchema.getDefaultInstance();
        }
        gamestateBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            coms309.server.Schema.GamestateSchema, coms309.server.Schema.GamestateSchema.Builder, coms309.server.Schema.GamestateSchemaOrBuilder>(
                (coms309.server.Schema.GamestateSchema) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 2;
      onChanged();;
      return gamestateBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        coms309.server.Schema.MessageSchema, coms309.server.Schema.MessageSchema.Builder, coms309.server.Schema.MessageSchemaOrBuilder> messageBuilder_;
    /**
     * <code>optional .coms309.server.MessageSchema message = 3;</code>
     */
    public boolean hasMessage() {
      return dataCase_ == 3;
    }
    /**
     * <code>optional .coms309.server.MessageSchema message = 3;</code>
     */
    public coms309.server.Schema.MessageSchema getMessage() {
      if (messageBuilder_ == null) {
        if (dataCase_ == 3) {
          return (coms309.server.Schema.MessageSchema) data_;
        }
        return coms309.server.Schema.MessageSchema.getDefaultInstance();
      } else {
        if (dataCase_ == 3) {
          return messageBuilder_.getMessage();
        }
        return coms309.server.Schema.MessageSchema.getDefaultInstance();
      }
    }
    /**
     * <code>optional .coms309.server.MessageSchema message = 3;</code>
     */
    public Builder setMessage(coms309.server.Schema.MessageSchema value) {
      if (messageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        messageBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>optional .coms309.server.MessageSchema message = 3;</code>
     */
    public Builder setMessage(
        coms309.server.Schema.MessageSchema.Builder builderForValue) {
      if (messageBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        messageBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>optional .coms309.server.MessageSchema message = 3;</code>
     */
    public Builder mergeMessage(coms309.server.Schema.MessageSchema value) {
      if (messageBuilder_ == null) {
        if (dataCase_ == 3 &&
            data_ != coms309.server.Schema.MessageSchema.getDefaultInstance()) {
          data_ = coms309.server.Schema.MessageSchema.newBuilder((coms309.server.Schema.MessageSchema) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 3) {
          messageBuilder_.mergeFrom(value);
        }
        messageBuilder_.setMessage(value);
      }
      dataCase_ = 3;
      return this;
    }
    /**
     * <code>optional .coms309.server.MessageSchema message = 3;</code>
     */
    public Builder clearMessage() {
      if (messageBuilder_ == null) {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 3) {
          dataCase_ = 0;
          data_ = null;
        }
        messageBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .coms309.server.MessageSchema message = 3;</code>
     */
    public coms309.server.Schema.MessageSchema.Builder getMessageBuilder() {
      return getMessageFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .coms309.server.MessageSchema message = 3;</code>
     */
    public coms309.server.Schema.MessageSchemaOrBuilder getMessageOrBuilder() {
      if ((dataCase_ == 3) && (messageBuilder_ != null)) {
        return messageBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 3) {
          return (coms309.server.Schema.MessageSchema) data_;
        }
        return coms309.server.Schema.MessageSchema.getDefaultInstance();
      }
    }
    /**
     * <code>optional .coms309.server.MessageSchema message = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        coms309.server.Schema.MessageSchema, coms309.server.Schema.MessageSchema.Builder, coms309.server.Schema.MessageSchemaOrBuilder> 
        getMessageFieldBuilder() {
      if (messageBuilder_ == null) {
        if (!(dataCase_ == 3)) {
          data_ = coms309.server.Schema.MessageSchema.getDefaultInstance();
        }
        messageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            coms309.server.Schema.MessageSchema, coms309.server.Schema.MessageSchema.Builder, coms309.server.Schema.MessageSchemaOrBuilder>(
                (coms309.server.Schema.MessageSchema) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 3;
      onChanged();;
      return messageBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        coms309.server.Schema.EntitySchema, coms309.server.Schema.EntitySchema.Builder, coms309.server.Schema.EntitySchemaOrBuilder> entityBuilder_;
    /**
     * <code>optional .coms309.server.EntitySchema entity = 4;</code>
     */
    public boolean hasEntity() {
      return dataCase_ == 4;
    }
    /**
     * <code>optional .coms309.server.EntitySchema entity = 4;</code>
     */
    public coms309.server.Schema.EntitySchema getEntity() {
      if (entityBuilder_ == null) {
        if (dataCase_ == 4) {
          return (coms309.server.Schema.EntitySchema) data_;
        }
        return coms309.server.Schema.EntitySchema.getDefaultInstance();
      } else {
        if (dataCase_ == 4) {
          return entityBuilder_.getMessage();
        }
        return coms309.server.Schema.EntitySchema.getDefaultInstance();
      }
    }
    /**
     * <code>optional .coms309.server.EntitySchema entity = 4;</code>
     */
    public Builder setEntity(coms309.server.Schema.EntitySchema value) {
      if (entityBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        data_ = value;
        onChanged();
      } else {
        entityBuilder_.setMessage(value);
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>optional .coms309.server.EntitySchema entity = 4;</code>
     */
    public Builder setEntity(
        coms309.server.Schema.EntitySchema.Builder builderForValue) {
      if (entityBuilder_ == null) {
        data_ = builderForValue.build();
        onChanged();
      } else {
        entityBuilder_.setMessage(builderForValue.build());
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>optional .coms309.server.EntitySchema entity = 4;</code>
     */
    public Builder mergeEntity(coms309.server.Schema.EntitySchema value) {
      if (entityBuilder_ == null) {
        if (dataCase_ == 4 &&
            data_ != coms309.server.Schema.EntitySchema.getDefaultInstance()) {
          data_ = coms309.server.Schema.EntitySchema.newBuilder((coms309.server.Schema.EntitySchema) data_)
              .mergeFrom(value).buildPartial();
        } else {
          data_ = value;
        }
        onChanged();
      } else {
        if (dataCase_ == 4) {
          entityBuilder_.mergeFrom(value);
        }
        entityBuilder_.setMessage(value);
      }
      dataCase_ = 4;
      return this;
    }
    /**
     * <code>optional .coms309.server.EntitySchema entity = 4;</code>
     */
    public Builder clearEntity() {
      if (entityBuilder_ == null) {
        if (dataCase_ == 4) {
          dataCase_ = 0;
          data_ = null;
          onChanged();
        }
      } else {
        if (dataCase_ == 4) {
          dataCase_ = 0;
          data_ = null;
        }
        entityBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>optional .coms309.server.EntitySchema entity = 4;</code>
     */
    public coms309.server.Schema.EntitySchema.Builder getEntityBuilder() {
      return getEntityFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .coms309.server.EntitySchema entity = 4;</code>
     */
    public coms309.server.Schema.EntitySchemaOrBuilder getEntityOrBuilder() {
      if ((dataCase_ == 4) && (entityBuilder_ != null)) {
        return entityBuilder_.getMessageOrBuilder();
      } else {
        if (dataCase_ == 4) {
          return (coms309.server.Schema.EntitySchema) data_;
        }
        return coms309.server.Schema.EntitySchema.getDefaultInstance();
      }
    }
    /**
     * <code>optional .coms309.server.EntitySchema entity = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        coms309.server.Schema.EntitySchema, coms309.server.Schema.EntitySchema.Builder, coms309.server.Schema.EntitySchemaOrBuilder> 
        getEntityFieldBuilder() {
      if (entityBuilder_ == null) {
        if (!(dataCase_ == 4)) {
          data_ = coms309.server.Schema.EntitySchema.getDefaultInstance();
        }
        entityBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            coms309.server.Schema.EntitySchema, coms309.server.Schema.EntitySchema.Builder, coms309.server.Schema.EntitySchemaOrBuilder>(
                (coms309.server.Schema.EntitySchema) data_,
                getParentForChildren(),
                isClean());
        data_ = null;
      }
      dataCase_ = 4;
      onChanged();;
      return entityBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:coms309.server.DataObjectSchema)
  }

  // @@protoc_insertion_point(class_scope:coms309.server.DataObjectSchema)
  private static final coms309.server.Schema.DataObjectSchema DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new coms309.server.Schema.DataObjectSchema();
  }

  public static coms309.server.Schema.DataObjectSchema getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<DataObjectSchema>
      PARSER = new com.google.protobuf.AbstractParser<DataObjectSchema>() {
    public DataObjectSchema parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataObjectSchema(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DataObjectSchema> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DataObjectSchema> getParserForType() {
    return PARSER;
  }

  public coms309.server.Schema.DataObjectSchema getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

