// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataObject.proto

package coms309.server.Schema;

public interface EntitySchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coms309.server.EntitySchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required uint32 x = 1;</code>
   */
  boolean hasX();
  /**
   * <code>required uint32 x = 1;</code>
   */
  int getX();

  /**
   * <code>required uint32 y = 2;</code>
   */
  boolean hasY();
  /**
   * <code>required uint32 y = 2;</code>
   */
  int getY();

  /**
   * <code>required uint32 objectId = 3;</code>
   */
  boolean hasObjectId();
  /**
   * <code>required uint32 objectId = 3;</code>
   */
  int getObjectId();

  /**
   * <code>required uint32 ownerId = 4;</code>
   */
  boolean hasOwnerId();
  /**
   * <code>required uint32 ownerId = 4;</code>
   */
  int getOwnerId();
}
