// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Entity.proto

package coms309.server.Schema;

public final class EntityProto {
  private EntityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coms309_server_EntitySchema_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coms309_server_EntitySchema_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Entity.proto\022\016coms309.server\"G\n\014Entity" +
      "Schema\022\t\n\001x\030\001 \002(\r\022\t\n\001y\030\002 \002(\r\022\020\n\010objectId" +
      "\030\004 \002(\r\022\017\n\007ownerId\030\005 \002(\rB&\n\025coms309.serve" +
      "r.SchemaB\013EntityProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_coms309_server_EntitySchema_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coms309_server_EntitySchema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coms309_server_EntitySchema_descriptor,
        new java.lang.String[] { "X", "Y", "ObjectId", "OwnerId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
