// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataObject.proto

package coms309.server.Schema;

public interface gameTickOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coms309.server.gameTick)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  java.util.List<coms309.server.Schema.gameTick.EnemyUpdate> 
      getEnemyUpdateList();
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  coms309.server.Schema.gameTick.EnemyUpdate getEnemyUpdate(int index);
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  int getEnemyUpdateCount();
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  java.util.List<? extends coms309.server.Schema.gameTick.EnemyUpdateOrBuilder> 
      getEnemyUpdateOrBuilderList();
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  coms309.server.Schema.gameTick.EnemyUpdateOrBuilder getEnemyUpdateOrBuilder(
      int index);
}
