// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataObject.proto

package coms309.server.Schema;

/**
 * <pre>
 *Buffer to hold game tick events
 * </pre>
 *
 * Protobuf type {@code coms309.server.gameTick}
 */
public  final class gameTick extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:coms309.server.gameTick)
    gameTickOrBuilder {
  // Use gameTick.newBuilder() to construct.
  private gameTick(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private gameTick() {
    enemyUpdate_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private gameTick(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownField(input, unknownFields,
                                   extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              enemyUpdate_ = new java.util.ArrayList<coms309.server.Schema.gameTick.EnemyUpdate>();
              mutable_bitField0_ |= 0x00000001;
            }
            enemyUpdate_.add(
                input.readMessage(coms309.server.Schema.gameTick.EnemyUpdate.PARSER, extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        enemyUpdate_ = java.util.Collections.unmodifiableList(enemyUpdate_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_gameTick_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_gameTick_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            coms309.server.Schema.gameTick.class, coms309.server.Schema.gameTick.Builder.class);
  }

  public interface EnemyUpdateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:coms309.server.gameTick.EnemyUpdate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 enemyId = 1;</code>
     */
    boolean hasEnemyId();
    /**
     * <code>required uint32 enemyId = 1;</code>
     */
    int getEnemyId();

    /**
     * <code>required uint32 health = 2;</code>
     */
    boolean hasHealth();
    /**
     * <code>required uint32 health = 2;</code>
     */
    int getHealth();

    /**
     * <code>optional uint32 attackedBy = 3;</code>
     */
    boolean hasAttackedBy();
    /**
     * <code>optional uint32 attackedBy = 3;</code>
     */
    int getAttackedBy();
  }
  /**
   * Protobuf type {@code coms309.server.gameTick.EnemyUpdate}
   */
  public  static final class EnemyUpdate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:coms309.server.gameTick.EnemyUpdate)
      EnemyUpdateOrBuilder {
    // Use EnemyUpdate.newBuilder() to construct.
    private EnemyUpdate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnemyUpdate() {
      enemyId_ = 0;
      health_ = 0;
      attackedBy_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnemyUpdate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              enemyId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              health_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              attackedBy_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_gameTick_EnemyUpdate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_gameTick_EnemyUpdate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coms309.server.Schema.gameTick.EnemyUpdate.class, coms309.server.Schema.gameTick.EnemyUpdate.Builder.class);
    }

    private int bitField0_;
    public static final int ENEMYID_FIELD_NUMBER = 1;
    private int enemyId_;
    /**
     * <code>required uint32 enemyId = 1;</code>
     */
    public boolean hasEnemyId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 enemyId = 1;</code>
     */
    public int getEnemyId() {
      return enemyId_;
    }

    public static final int HEALTH_FIELD_NUMBER = 2;
    private int health_;
    /**
     * <code>required uint32 health = 2;</code>
     */
    public boolean hasHealth() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 health = 2;</code>
     */
    public int getHealth() {
      return health_;
    }

    public static final int ATTACKEDBY_FIELD_NUMBER = 3;
    private int attackedBy_;
    /**
     * <code>optional uint32 attackedBy = 3;</code>
     */
    public boolean hasAttackedBy() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint32 attackedBy = 3;</code>
     */
    public int getAttackedBy() {
      return attackedBy_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEnemyId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHealth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, enemyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, health_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, attackedBy_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, enemyId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, health_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, attackedBy_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof coms309.server.Schema.gameTick.EnemyUpdate)) {
        return super.equals(obj);
      }
      coms309.server.Schema.gameTick.EnemyUpdate other = (coms309.server.Schema.gameTick.EnemyUpdate) obj;

      boolean result = true;
      result = result && (hasEnemyId() == other.hasEnemyId());
      if (hasEnemyId()) {
        result = result && (getEnemyId()
            == other.getEnemyId());
      }
      result = result && (hasHealth() == other.hasHealth());
      if (hasHealth()) {
        result = result && (getHealth()
            == other.getHealth());
      }
      result = result && (hasAttackedBy() == other.hasAttackedBy());
      if (hasAttackedBy()) {
        result = result && (getAttackedBy()
            == other.getAttackedBy());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasEnemyId()) {
        hash = (37 * hash) + ENEMYID_FIELD_NUMBER;
        hash = (53 * hash) + getEnemyId();
      }
      if (hasHealth()) {
        hash = (37 * hash) + HEALTH_FIELD_NUMBER;
        hash = (53 * hash) + getHealth();
      }
      if (hasAttackedBy()) {
        hash = (37 * hash) + ATTACKEDBY_FIELD_NUMBER;
        hash = (53 * hash) + getAttackedBy();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static coms309.server.Schema.gameTick.EnemyUpdate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coms309.server.Schema.gameTick.EnemyUpdate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coms309.server.Schema.gameTick.EnemyUpdate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static coms309.server.Schema.gameTick.EnemyUpdate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static coms309.server.Schema.gameTick.EnemyUpdate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coms309.server.Schema.gameTick.EnemyUpdate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static coms309.server.Schema.gameTick.EnemyUpdate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static coms309.server.Schema.gameTick.EnemyUpdate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static coms309.server.Schema.gameTick.EnemyUpdate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static coms309.server.Schema.gameTick.EnemyUpdate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(coms309.server.Schema.gameTick.EnemyUpdate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code coms309.server.gameTick.EnemyUpdate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:coms309.server.gameTick.EnemyUpdate)
        coms309.server.Schema.gameTick.EnemyUpdateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_gameTick_EnemyUpdate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_gameTick_EnemyUpdate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                coms309.server.Schema.gameTick.EnemyUpdate.class, coms309.server.Schema.gameTick.EnemyUpdate.Builder.class);
      }

      // Construct using coms309.server.Schema.gameTick.EnemyUpdate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        enemyId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        health_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        attackedBy_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_gameTick_EnemyUpdate_descriptor;
      }

      public coms309.server.Schema.gameTick.EnemyUpdate getDefaultInstanceForType() {
        return coms309.server.Schema.gameTick.EnemyUpdate.getDefaultInstance();
      }

      public coms309.server.Schema.gameTick.EnemyUpdate build() {
        coms309.server.Schema.gameTick.EnemyUpdate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public coms309.server.Schema.gameTick.EnemyUpdate buildPartial() {
        coms309.server.Schema.gameTick.EnemyUpdate result = new coms309.server.Schema.gameTick.EnemyUpdate(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.enemyId_ = enemyId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.health_ = health_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.attackedBy_ = attackedBy_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof coms309.server.Schema.gameTick.EnemyUpdate) {
          return mergeFrom((coms309.server.Schema.gameTick.EnemyUpdate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(coms309.server.Schema.gameTick.EnemyUpdate other) {
        if (other == coms309.server.Schema.gameTick.EnemyUpdate.getDefaultInstance()) return this;
        if (other.hasEnemyId()) {
          setEnemyId(other.getEnemyId());
        }
        if (other.hasHealth()) {
          setHealth(other.getHealth());
        }
        if (other.hasAttackedBy()) {
          setAttackedBy(other.getAttackedBy());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEnemyId()) {
          return false;
        }
        if (!hasHealth()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        coms309.server.Schema.gameTick.EnemyUpdate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (coms309.server.Schema.gameTick.EnemyUpdate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int enemyId_ ;
      /**
       * <code>required uint32 enemyId = 1;</code>
       */
      public boolean hasEnemyId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 enemyId = 1;</code>
       */
      public int getEnemyId() {
        return enemyId_;
      }
      /**
       * <code>required uint32 enemyId = 1;</code>
       */
      public Builder setEnemyId(int value) {
        bitField0_ |= 0x00000001;
        enemyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 enemyId = 1;</code>
       */
      public Builder clearEnemyId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        enemyId_ = 0;
        onChanged();
        return this;
      }

      private int health_ ;
      /**
       * <code>required uint32 health = 2;</code>
       */
      public boolean hasHealth() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 health = 2;</code>
       */
      public int getHealth() {
        return health_;
      }
      /**
       * <code>required uint32 health = 2;</code>
       */
      public Builder setHealth(int value) {
        bitField0_ |= 0x00000002;
        health_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 health = 2;</code>
       */
      public Builder clearHealth() {
        bitField0_ = (bitField0_ & ~0x00000002);
        health_ = 0;
        onChanged();
        return this;
      }

      private int attackedBy_ ;
      /**
       * <code>optional uint32 attackedBy = 3;</code>
       */
      public boolean hasAttackedBy() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint32 attackedBy = 3;</code>
       */
      public int getAttackedBy() {
        return attackedBy_;
      }
      /**
       * <code>optional uint32 attackedBy = 3;</code>
       */
      public Builder setAttackedBy(int value) {
        bitField0_ |= 0x00000004;
        attackedBy_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 attackedBy = 3;</code>
       */
      public Builder clearAttackedBy() {
        bitField0_ = (bitField0_ & ~0x00000004);
        attackedBy_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:coms309.server.gameTick.EnemyUpdate)
    }

    // @@protoc_insertion_point(class_scope:coms309.server.gameTick.EnemyUpdate)
    private static final coms309.server.Schema.gameTick.EnemyUpdate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new coms309.server.Schema.gameTick.EnemyUpdate();
    }

    public static coms309.server.Schema.gameTick.EnemyUpdate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EnemyUpdate>
        PARSER = new com.google.protobuf.AbstractParser<EnemyUpdate>() {
      public EnemyUpdate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EnemyUpdate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnemyUpdate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnemyUpdate> getParserForType() {
      return PARSER;
    }

    public coms309.server.Schema.gameTick.EnemyUpdate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int ENEMYUPDATE_FIELD_NUMBER = 1;
  private java.util.List<coms309.server.Schema.gameTick.EnemyUpdate> enemyUpdate_;
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  public java.util.List<coms309.server.Schema.gameTick.EnemyUpdate> getEnemyUpdateList() {
    return enemyUpdate_;
  }
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  public java.util.List<? extends coms309.server.Schema.gameTick.EnemyUpdateOrBuilder> 
      getEnemyUpdateOrBuilderList() {
    return enemyUpdate_;
  }
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  public int getEnemyUpdateCount() {
    return enemyUpdate_.size();
  }
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  public coms309.server.Schema.gameTick.EnemyUpdate getEnemyUpdate(int index) {
    return enemyUpdate_.get(index);
  }
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  public coms309.server.Schema.gameTick.EnemyUpdateOrBuilder getEnemyUpdateOrBuilder(
      int index) {
    return enemyUpdate_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    for (int i = 0; i < getEnemyUpdateCount(); i++) {
      if (!getEnemyUpdate(i).isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
    }
    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < enemyUpdate_.size(); i++) {
      output.writeMessage(1, enemyUpdate_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < enemyUpdate_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, enemyUpdate_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof coms309.server.Schema.gameTick)) {
      return super.equals(obj);
    }
    coms309.server.Schema.gameTick other = (coms309.server.Schema.gameTick) obj;

    boolean result = true;
    result = result && getEnemyUpdateList()
        .equals(other.getEnemyUpdateList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    if (getEnemyUpdateCount() > 0) {
      hash = (37 * hash) + ENEMYUPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getEnemyUpdateList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static coms309.server.Schema.gameTick parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static coms309.server.Schema.gameTick parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static coms309.server.Schema.gameTick parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static coms309.server.Schema.gameTick parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static coms309.server.Schema.gameTick parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static coms309.server.Schema.gameTick parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static coms309.server.Schema.gameTick parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static coms309.server.Schema.gameTick parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static coms309.server.Schema.gameTick parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static coms309.server.Schema.gameTick parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(coms309.server.Schema.gameTick prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Buffer to hold game tick events
   * </pre>
   *
   * Protobuf type {@code coms309.server.gameTick}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:coms309.server.gameTick)
      coms309.server.Schema.gameTickOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_gameTick_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_gameTick_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              coms309.server.Schema.gameTick.class, coms309.server.Schema.gameTick.Builder.class);
    }

    // Construct using coms309.server.Schema.gameTick.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEnemyUpdateFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (enemyUpdateBuilder_ == null) {
        enemyUpdate_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        enemyUpdateBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return coms309.server.Schema.DataObjectProto.internal_static_coms309_server_gameTick_descriptor;
    }

    public coms309.server.Schema.gameTick getDefaultInstanceForType() {
      return coms309.server.Schema.gameTick.getDefaultInstance();
    }

    public coms309.server.Schema.gameTick build() {
      coms309.server.Schema.gameTick result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public coms309.server.Schema.gameTick buildPartial() {
      coms309.server.Schema.gameTick result = new coms309.server.Schema.gameTick(this);
      int from_bitField0_ = bitField0_;
      if (enemyUpdateBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          enemyUpdate_ = java.util.Collections.unmodifiableList(enemyUpdate_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.enemyUpdate_ = enemyUpdate_;
      } else {
        result.enemyUpdate_ = enemyUpdateBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof coms309.server.Schema.gameTick) {
        return mergeFrom((coms309.server.Schema.gameTick)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(coms309.server.Schema.gameTick other) {
      if (other == coms309.server.Schema.gameTick.getDefaultInstance()) return this;
      if (enemyUpdateBuilder_ == null) {
        if (!other.enemyUpdate_.isEmpty()) {
          if (enemyUpdate_.isEmpty()) {
            enemyUpdate_ = other.enemyUpdate_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEnemyUpdateIsMutable();
            enemyUpdate_.addAll(other.enemyUpdate_);
          }
          onChanged();
        }
      } else {
        if (!other.enemyUpdate_.isEmpty()) {
          if (enemyUpdateBuilder_.isEmpty()) {
            enemyUpdateBuilder_.dispose();
            enemyUpdateBuilder_ = null;
            enemyUpdate_ = other.enemyUpdate_;
            bitField0_ = (bitField0_ & ~0x00000001);
            enemyUpdateBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEnemyUpdateFieldBuilder() : null;
          } else {
            enemyUpdateBuilder_.addAllMessages(other.enemyUpdate_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      for (int i = 0; i < getEnemyUpdateCount(); i++) {
        if (!getEnemyUpdate(i).isInitialized()) {
          return false;
        }
      }
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      coms309.server.Schema.gameTick parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (coms309.server.Schema.gameTick) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<coms309.server.Schema.gameTick.EnemyUpdate> enemyUpdate_ =
      java.util.Collections.emptyList();
    private void ensureEnemyUpdateIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        enemyUpdate_ = new java.util.ArrayList<coms309.server.Schema.gameTick.EnemyUpdate>(enemyUpdate_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        coms309.server.Schema.gameTick.EnemyUpdate, coms309.server.Schema.gameTick.EnemyUpdate.Builder, coms309.server.Schema.gameTick.EnemyUpdateOrBuilder> enemyUpdateBuilder_;

    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public java.util.List<coms309.server.Schema.gameTick.EnemyUpdate> getEnemyUpdateList() {
      if (enemyUpdateBuilder_ == null) {
        return java.util.Collections.unmodifiableList(enemyUpdate_);
      } else {
        return enemyUpdateBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public int getEnemyUpdateCount() {
      if (enemyUpdateBuilder_ == null) {
        return enemyUpdate_.size();
      } else {
        return enemyUpdateBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public coms309.server.Schema.gameTick.EnemyUpdate getEnemyUpdate(int index) {
      if (enemyUpdateBuilder_ == null) {
        return enemyUpdate_.get(index);
      } else {
        return enemyUpdateBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public Builder setEnemyUpdate(
        int index, coms309.server.Schema.gameTick.EnemyUpdate value) {
      if (enemyUpdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnemyUpdateIsMutable();
        enemyUpdate_.set(index, value);
        onChanged();
      } else {
        enemyUpdateBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public Builder setEnemyUpdate(
        int index, coms309.server.Schema.gameTick.EnemyUpdate.Builder builderForValue) {
      if (enemyUpdateBuilder_ == null) {
        ensureEnemyUpdateIsMutable();
        enemyUpdate_.set(index, builderForValue.build());
        onChanged();
      } else {
        enemyUpdateBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public Builder addEnemyUpdate(coms309.server.Schema.gameTick.EnemyUpdate value) {
      if (enemyUpdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnemyUpdateIsMutable();
        enemyUpdate_.add(value);
        onChanged();
      } else {
        enemyUpdateBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public Builder addEnemyUpdate(
        int index, coms309.server.Schema.gameTick.EnemyUpdate value) {
      if (enemyUpdateBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEnemyUpdateIsMutable();
        enemyUpdate_.add(index, value);
        onChanged();
      } else {
        enemyUpdateBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public Builder addEnemyUpdate(
        coms309.server.Schema.gameTick.EnemyUpdate.Builder builderForValue) {
      if (enemyUpdateBuilder_ == null) {
        ensureEnemyUpdateIsMutable();
        enemyUpdate_.add(builderForValue.build());
        onChanged();
      } else {
        enemyUpdateBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public Builder addEnemyUpdate(
        int index, coms309.server.Schema.gameTick.EnemyUpdate.Builder builderForValue) {
      if (enemyUpdateBuilder_ == null) {
        ensureEnemyUpdateIsMutable();
        enemyUpdate_.add(index, builderForValue.build());
        onChanged();
      } else {
        enemyUpdateBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public Builder addAllEnemyUpdate(
        java.lang.Iterable<? extends coms309.server.Schema.gameTick.EnemyUpdate> values) {
      if (enemyUpdateBuilder_ == null) {
        ensureEnemyUpdateIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, enemyUpdate_);
        onChanged();
      } else {
        enemyUpdateBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public Builder clearEnemyUpdate() {
      if (enemyUpdateBuilder_ == null) {
        enemyUpdate_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        enemyUpdateBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public Builder removeEnemyUpdate(int index) {
      if (enemyUpdateBuilder_ == null) {
        ensureEnemyUpdateIsMutable();
        enemyUpdate_.remove(index);
        onChanged();
      } else {
        enemyUpdateBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public coms309.server.Schema.gameTick.EnemyUpdate.Builder getEnemyUpdateBuilder(
        int index) {
      return getEnemyUpdateFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public coms309.server.Schema.gameTick.EnemyUpdateOrBuilder getEnemyUpdateOrBuilder(
        int index) {
      if (enemyUpdateBuilder_ == null) {
        return enemyUpdate_.get(index);  } else {
        return enemyUpdateBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public java.util.List<? extends coms309.server.Schema.gameTick.EnemyUpdateOrBuilder> 
         getEnemyUpdateOrBuilderList() {
      if (enemyUpdateBuilder_ != null) {
        return enemyUpdateBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(enemyUpdate_);
      }
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public coms309.server.Schema.gameTick.EnemyUpdate.Builder addEnemyUpdateBuilder() {
      return getEnemyUpdateFieldBuilder().addBuilder(
          coms309.server.Schema.gameTick.EnemyUpdate.getDefaultInstance());
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public coms309.server.Schema.gameTick.EnemyUpdate.Builder addEnemyUpdateBuilder(
        int index) {
      return getEnemyUpdateFieldBuilder().addBuilder(
          index, coms309.server.Schema.gameTick.EnemyUpdate.getDefaultInstance());
    }
    /**
     * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
     */
    public java.util.List<coms309.server.Schema.gameTick.EnemyUpdate.Builder> 
         getEnemyUpdateBuilderList() {
      return getEnemyUpdateFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        coms309.server.Schema.gameTick.EnemyUpdate, coms309.server.Schema.gameTick.EnemyUpdate.Builder, coms309.server.Schema.gameTick.EnemyUpdateOrBuilder> 
        getEnemyUpdateFieldBuilder() {
      if (enemyUpdateBuilder_ == null) {
        enemyUpdateBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            coms309.server.Schema.gameTick.EnemyUpdate, coms309.server.Schema.gameTick.EnemyUpdate.Builder, coms309.server.Schema.gameTick.EnemyUpdateOrBuilder>(
                enemyUpdate_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        enemyUpdate_ = null;
      }
      return enemyUpdateBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:coms309.server.gameTick)
  }

  // @@protoc_insertion_point(class_scope:coms309.server.gameTick)
  private static final coms309.server.Schema.gameTick DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new coms309.server.Schema.gameTick();
  }

  public static coms309.server.Schema.gameTick getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<gameTick>
      PARSER = new com.google.protobuf.AbstractParser<gameTick>() {
    public gameTick parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new gameTick(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<gameTick> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<gameTick> getParserForType() {
    return PARSER;
  }

  public coms309.server.Schema.gameTick getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

