// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Gamestate.proto

package coms309.server.Schema;

public final class GamestateProto {
  private GamestateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coms309_server_GamestateSchema_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coms309_server_GamestateSchema_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_coms309_server_GamestateSchema_Player_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_coms309_server_GamestateSchema_Player_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Gamestate.proto\022\016coms309.server\"\255\001\n\017Ga" +
      "mestateSchema\022\022\n\ndifficulty\030\001 \001(\r\022\016\n\006sta" +
      "tus\030\002 \001(\r\022\013\n\003map\030\003 \001(\r\022\r\n\005round\030\004 \001(\r\0227\n" +
      "\007players\030\005 \003(\0132&.coms309.server.Gamestat" +
      "eSchema.Player\032!\n\006Player\022\013\n\003pid\030\001 \001(\005\022\n\n" +
      "\002id\030\002 \001(\tB)\n\025coms309.server.SchemaB\016Game" +
      "stateProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_coms309_server_GamestateSchema_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_coms309_server_GamestateSchema_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coms309_server_GamestateSchema_descriptor,
        new java.lang.String[] { "Difficulty", "Status", "Map", "Round", "Players", });
    internal_static_coms309_server_GamestateSchema_Player_descriptor =
      internal_static_coms309_server_GamestateSchema_descriptor.getNestedTypes().get(0);
    internal_static_coms309_server_GamestateSchema_Player_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_coms309_server_GamestateSchema_Player_descriptor,
        new java.lang.String[] { "Pid", "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
