// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataObject.proto

package com.se309.schema;

public interface gameTickOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coms309.server.gameTick)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  java.util.List<com.se309.schema.gameTick.EnemyUpdate> 
      getEnemyUpdateList();
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  com.se309.schema.gameTick.EnemyUpdate getEnemyUpdate(int index);
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  int getEnemyUpdateCount();
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  java.util.List<? extends com.se309.schema.gameTick.EnemyUpdateOrBuilder> 
      getEnemyUpdateOrBuilderList();
  /**
   * <code>repeated .coms309.server.gameTick.EnemyUpdate enemyUpdate = 1;</code>
   */
  com.se309.schema.gameTick.EnemyUpdateOrBuilder getEnemyUpdateOrBuilder(
          int index);
}
