// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DataObject.proto

package com.se309.schema;

public interface GamestateSchemaOrBuilder extends
    // @@protoc_insertion_point(interface_extends:coms309.server.GamestateSchema)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint32 difficulty = 1;</code>
   */
  boolean hasDifficulty();
  /**
   * <code>optional uint32 difficulty = 1;</code>
   */
  int getDifficulty();

  /**
   * <code>optional uint32 status = 2;</code>
   */
  boolean hasStatus();
  /**
   * <code>optional uint32 status = 2;</code>
   */
  int getStatus();

  /**
   * <code>optional uint32 map = 3;</code>
   */
  boolean hasMap();
  /**
   * <code>optional uint32 map = 3;</code>
   */
  int getMap();

  /**
   * <code>optional uint32 round = 4;</code>
   */
  boolean hasRound();
  /**
   * <code>optional uint32 round = 4;</code>
   */
  int getRound();

  /**
   * <code>repeated .coms309.server.GamestateSchema.Player players = 5;</code>
   */
  java.util.List<com.se309.schema.GamestateSchema.Player> 
      getPlayersList();
  /**
   * <code>repeated .coms309.server.GamestateSchema.Player players = 5;</code>
   */
  com.se309.schema.GamestateSchema.Player getPlayers(int index);
  /**
   * <code>repeated .coms309.server.GamestateSchema.Player players = 5;</code>
   */
  int getPlayersCount();
  /**
   * <code>repeated .coms309.server.GamestateSchema.Player players = 5;</code>
   */
  java.util.List<? extends com.se309.schema.GamestateSchema.PlayerOrBuilder> 
      getPlayersOrBuilderList();
  /**
   * <code>repeated .coms309.server.GamestateSchema.Player players = 5;</code>
   */
  com.se309.schema.GamestateSchema.PlayerOrBuilder getPlayersOrBuilder(
          int index);
}
